site_name: Ado Conte
repo_name: adoloconte/adoloconte.github.io
site_url: https://adoloconte.github.io
repo_url: https://github.com/adoloconte/adoloconte.github.io
theme:
  name: material
  custom_dir: theme
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - def_list
  - md_in_html
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


plugins:
  - search
  - exclude-search:
      exclude:
        - newsletter/*
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter

nav:
  - index.md
  - Paint: paint/20230303.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aloconte
    - icon: fontawesome/solid/rss
      link: https://aloconte.github.io/newsletter/0_newsletter_index