site_name: "Ado's Doco"
site_description: "Ado's documentation"
site_author: 'Ado Loconte'

repo_url: https://github.com/aloconte/aloconte.github.io

theme:
    name: null
    custom_dir: mkdocs_dark
    # default from mkdocs_theme.yml
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true

nav:
    - AWS: aws.md
    - K8S: kubernetes.md
    - CICD:
        - Jenkins: jenkins.md
        - Sonarqube: sample-a1.md
        - Fortify: sample-a2.md
        - Feedback: sample-b.md

markdown_extensions:
    - attr_list
    - md_in_html
    - toc:
        permalink: '#'

plugins:
    - search # necessary for search to work
    - git-revision-date-localized

#extra:
#    version: 0.0.1
